name: E2E Poc
run-name: e2e poc

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  wait_for_e2e:
    name: 'Set wait for e2e'
    runs-on: ubuntu-latest
    steps:
      - name: Login into github cli
        env:
          GIT_TOKEN: '${{ secrets.TOKEN }}'
        run: echo ${GIT_TOKEN} | gh auth login --with-token

      - name: Get pr branch
        env:
          PR_BODY: '${{ github.event.pull_request.body }}'
        run: |
          PR=$(echo "$PR_BODY" | grep "has-front-pr=" | { grep -v grep || true; })
          IFS='='
          read -ra arr <<< "$PR"
          PR_URL=$(echo ${arr[1]} | xargs echo -n)
          if [[ "$PR_URL" == "true" ]]
          then
            BACK_HEAD_SHA="${{ github.event.pull_request.head.sha }}"

            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/ElrikSouza/board-api/statuses/$BACK_HEAD_SHA \
              -f state='pending' \
              -f description='Esperando testes do front terminarem' \
              -f context='E2E Test'
          else
            echo "No PR url detected."
          fi

